name: Run Python Schedules
run-name: ${{ github.actor }} is running the test schedules.
on: [push]

#on:
#  pull_request:
#    branches:
#      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl perl cpanminus libpq-dev libffi-dev libssl-dev libkrb5-dev zlib1g-dev python3-dotenv python3-psycopg2 python-pip

      - name: Make install Python
        run: make install-python

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv psycopg psycopg2

      - name: Check the Python wheel build
        run: |
          . venv/bin/activate
          make pip

      - name: source environment variables
        run: |
          source t/lib/config.env
          echo $REPO

      - name: Run Python scripts
        run: |
          python runner.py -s schedule_files/script_file

      - name: Upload Log File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest-log
          path: latest.log      

      - name: Verify success
        if: success()
        run: echo "All scripts executed successfully. Pull request can be merged."



