name: Run Python Schedules
run-name: ${{ github.actor }} is running the test schedules.
on: [push]

#on:
#  pull_request:
#    branches:
#      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if required)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 3: Source environment
      - name: source environment variables
        run: |
          source t/lib/config.env

      # Step 4: Run the Python scripts with runner.py
      - name: Run Python scripts
        run: |
          python runner.py -s schedule_files/setup
          python runner.py -s schedule_files/testing
          python runner.py -s schedule_files/teardown

      # Step 5: Verify output (GitHub Actions should fail the job if any script raises an error)
      - name: Verify success
        if: success()
        run: echo "All scripts executed successfully. Pull request can be merged."



