name: Run Python Schedules
run-name: ${{ github.actor }} is running the test schedules.
on: [push]

#on:
#  pull_request:
#    branches:
#      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Python dependencies with pip
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv psycopg
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Install apt dependencies
      - name: Install apt dependencies
        run: |
          sudo apt update -y
          sudo apt install -y curl perl cpanminus

#      # Step 5: Install yum dependencies
#      - name: Update and install yum dependencies for perl scripts
#        run: |
#          sudo yum update -y
#          sudo yum install -y perl-devel

#      # Step 6: Install dnf dependencies
#      - name: Update and install dnf dependencies for perl scripts
#        run: |
#          sudo dnf update -y
#          sudo dnf install -y perl-File-Which perl-Try-Tiny perl-JSON perl-List-MoreUtils perl-DBD-Pg perl-DBD-DBI python3-psycopg2

      # Step 6: Source environment variables
      - name: source environment variables
        run: |
          source t/lib/config.env
          echo $REPO

      # Step 5: Run the Python scripts with runner.py
      - name: Run Python scripts
        run: |
          python runner.py -s schedule_files/setup
          python runner.py -s schedule_files/testing
          python runner.py -s schedule_files/teardown

      # Step 6: Verify output (GitHub Actions should fail the job if any script raises an error)
      - name: Verify success
        if: success()
        run: echo "All scripts executed successfully. Pull request can be merged."



